default: &default
  adapter: postgresql
  encoding: unicode
  username: haystack
  password: secret
  host: localhost
  pool: 5

development:
  <<: *default
  database: haystack_development
  host: localhost
  username: dev
  password: '123'
  port: 5432

test:
  <<: *default
  database: haystack_test

production:
  <<: *default
  database: haystack_production
  username: deploy
  password: <%= ENV['HAYSTACK_DATABASE_PASSWORD'] %>
